---
title: "Chart"
author: "Rosauro and Joe"
date: "March 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)
options(scipen = '999')
```

```{r}
if(!require('tidyverse')){
  install.packages('tidyverse')
}
if(!require('ggplot2')){
  install.packages('ggplot2')
}
if(!require('readxl')){
  install.packages('readxl')
}
if(!require('readxl')){
  install.packages('readxl')
}
if(!require('RColorBrewer')){
  install.packages('RColorBrewer')
}
if(!require('plotly')){
  install.packages('plotly')
}
if(!require('ggthemes')){
  install.packages('ggthemes')
}
```


```{r}
# Read data into R
df <- read_excel('Grafica Joe v3.xlsx',
                 skip = 1)
names(df)[1] <- 'key'

# Make long
df <- gather(df, time, value, `0h`:`216h`)

# Get hours
df$hours <- as.numeric(gsub('h', '', df$time))

# Get value as percent of first
df <- df %>%
  group_by(key) %>%
  mutate(p = value / first(value) * 100) %>%
  ungroup

# Arrange by hours
df <- df %>%
  arrange(hours)

# manually set to 0 parisetemia
df$value[df$key == 'Parasitemia' &
           df$hours == 216] <- 0
df$p[df$key == 'Parasitemia' &
           df$hours == 216] <- 0

# Remove NA values
df <- df %>%
  filter(!is.na(p))


# Filter down
df <- df %>%
  filter(key %in% c('Hemoglobin', 'Parasitemia', 'White Blood Cells'))


# Multiply WBC by 1000
df$value[df$key == 'White Blood Cells'] <-
  df$value[df$key == 'White Blood Cells'] * 1000

# plot
cols <- colorRampPalette(brewer.pal(n = 9, name = 'Set1'))(length(unique(df$key)))

# Make a sub dataframe for labeling hgb cut points
hgb <- df %>% filter(grepl('Hemoglobin', key))
hgb$time <- as.numeric(gsub('h', '', hgb$time))
# need to interpolate the value at the unknown hours
left <- data_frame(time = seq(0, max(hgb$time), by = 1))
hgb <- left_join(left, hgb)
hgb$p <- zoo::na.approx(object = hgb$p,
                            x = hgb$time)
hgb$value <- zoo::na.approx(object = hgb$value,
                        x = hgb$time)
hgb <- hgb %>% filter(time %in% c(6, 98, 174))
hgb$hours <- hgb$time
hgb$time <- paste0(hgb$time, 'h')

# Get better labels

greeks <- list(
  bquote('HGB (g/dL)'),
  bquote(.('Parasitemia (parasites /') ~ mu*.('L)')),
  # bquote(.('joe'),mu),
  bquote(.('WBCC (Leococytes /') ~ mu*.('L)')))

greeks2 <- 
  c('HGB (g/dL)',
    'Parasitemia (parasites/microlitre)',
    'WBCC (Leococytes/microlitre')

# plot
cols <- colorRampPalette(brewer.pal(n = 9, name = 'Set1'))(length(unique(df$key)))

# Add the points
hgb$key <- 'Hemoglobin'
hgb$triangle <- hgb$value

df <- bind_rows(hgb, df)

g <- ggplot() +
  geom_line(data = df,
            aes(x = hours,
                y = value,
                group = key,
                color = key)) +
  geom_point(data = df,
             aes(x = hours,
                 y = triangle),
             pch = 6,
             size = 3,
             col = cols[1]) +
  labs(x = 'Time after recruitment (hours)',
       y = 'Value') +
  geom_point(data = hgb,
             aes(x = hours,
                 y = value),
             pch = 6,
             size = 3,
             col = cols[1]) +
  # geom_hline(yintercept = c(100), alpha = 0.6, lty = 3) +
  theme_hc() 

```

# Static plot

## Rows

```{r}
g   + scale_colour_manual(name = '',
                      values=cols,
                      labels=greeks) +
    facet_wrap(~key, scales = 'free_y',
             ncol = 1)
```

## Columns

```{r}
g   + scale_colour_manual(name = '',
                      values=cols,
                      labels=greeks) +
    facet_wrap(~key, scales = 'free_y',
             ncol = 3)
```

# Interactive plot

```{r}
# Rename wbc
df$key <-
  ifelse(df$key == 'White Blood Cells',
         'WBCC (leucocytes/microlitre)',
         # expression(paste0("WBCC (leucocytes/)", mu, 'L')),
         df$key)

# Rename parasitemia
df <- df %>%
  mutate(key = ifelse(key == 'Parasitemia', 'Parasitemia (parasites/microlitre)',
                      ifelse(key == 'Hemoglobin', 'HGB (g/dL)',
                             key)))

g <- ggplot() +
  geom_line(data = df,
            aes(x = hours,
                y = value,
                group = key,
                color = key)) +
  geom_point(data = df,
             aes(x = hours,
                 y = triangle),
             pch = 6,
             size = 3,
             col = cols[1]) +
  labs(x = 'Time after recruitment (hours)',
       y = '') +
  geom_hline(yintercept = c(100), alpha = 0.6, lty = 3) +
  theme_gdocs() +
  scale_colour_manual(name = '',
                      values=cols) 
```

## Rows

```{r}
plotly::ggplotly(g +
  facet_wrap(~key, scales = 'free_y',
             ncol = 1), 
                 tooltip = c('x', 'y', 'z'))
    
```


## Columns

```{r}
plotly::ggplotly(g +
  facet_wrap(~key, scales = 'free_y',
             ncol = 3), 
                 tooltip = c('x', 'y', 'z'))
    
```
